# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class MyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.jsSayHello = channel.unary_unary(
                '/myservice.MyService/jsSayHello',
                request_serializer=service__pb2.JsHelloRequest.SerializeToString,
                response_deserializer=service__pb2.JsHelloResponse.FromString,
                _registered_method=True)
        self.jsSum = channel.unary_unary(
                '/myservice.MyService/jsSum',
                request_serializer=service__pb2.JsSumRequest.SerializeToString,
                response_deserializer=service__pb2.JsSumResponse.FromString,
                _registered_method=True)
        self.pySayHello = channel.unary_unary(
                '/myservice.MyService/pySayHello',
                request_serializer=service__pb2.PyHelloRequest.SerializeToString,
                response_deserializer=service__pb2.PyHelloResponse.FromString,
                _registered_method=True)
        self.pySum = channel.unary_unary(
                '/myservice.MyService/pySum',
                request_serializer=service__pb2.PySumRequest.SerializeToString,
                response_deserializer=service__pb2.PySumResponse.FromString,
                _registered_method=True)


class MyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def jsSayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def jsSum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pySayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pySum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'jsSayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.jsSayHello,
                    request_deserializer=service__pb2.JsHelloRequest.FromString,
                    response_serializer=service__pb2.JsHelloResponse.SerializeToString,
            ),
            'jsSum': grpc.unary_unary_rpc_method_handler(
                    servicer.jsSum,
                    request_deserializer=service__pb2.JsSumRequest.FromString,
                    response_serializer=service__pb2.JsSumResponse.SerializeToString,
            ),
            'pySayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.pySayHello,
                    request_deserializer=service__pb2.PyHelloRequest.FromString,
                    response_serializer=service__pb2.PyHelloResponse.SerializeToString,
            ),
            'pySum': grpc.unary_unary_rpc_method_handler(
                    servicer.pySum,
                    request_deserializer=service__pb2.PySumRequest.FromString,
                    response_serializer=service__pb2.PySumResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myservice.MyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('myservice.MyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def jsSayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myservice.MyService/jsSayHello',
            service__pb2.JsHelloRequest.SerializeToString,
            service__pb2.JsHelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def jsSum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myservice.MyService/jsSum',
            service__pb2.JsSumRequest.SerializeToString,
            service__pb2.JsSumResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def pySayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myservice.MyService/pySayHello',
            service__pb2.PyHelloRequest.SerializeToString,
            service__pb2.PyHelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def pySum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myservice.MyService/pySum',
            service__pb2.PySumRequest.SerializeToString,
            service__pb2.PySumResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
