# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\tmyservice\"\x1e\n\x0eJsHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\"\n\x0fJsHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"*\n\x0cJsSumRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"\x1f\n\rJsSumResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x1e\n\x0ePyHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\"\n\x0fPyHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"*\n\x0cPySumRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"\x1f\n\rPySumResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\x8d\x02\n\tMyService\x12\x43\n\njsSayHello\x12\x19.myservice.JsHelloRequest\x1a\x1a.myservice.JsHelloResponse\x12:\n\x05jsSum\x12\x17.myservice.JsSumRequest\x1a\x18.myservice.JsSumResponse\x12\x43\n\npySayHello\x12\x19.myservice.PyHelloRequest\x1a\x1a.myservice.PyHelloResponse\x12:\n\x05pySum\x12\x17.myservice.PySumRequest\x1a\x18.myservice.PySumResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JSHELLOREQUEST']._serialized_start=28
  _globals['_JSHELLOREQUEST']._serialized_end=58
  _globals['_JSHELLORESPONSE']._serialized_start=60
  _globals['_JSHELLORESPONSE']._serialized_end=94
  _globals['_JSSUMREQUEST']._serialized_start=96
  _globals['_JSSUMREQUEST']._serialized_end=138
  _globals['_JSSUMRESPONSE']._serialized_start=140
  _globals['_JSSUMRESPONSE']._serialized_end=171
  _globals['_PYHELLOREQUEST']._serialized_start=173
  _globals['_PYHELLOREQUEST']._serialized_end=203
  _globals['_PYHELLORESPONSE']._serialized_start=205
  _globals['_PYHELLORESPONSE']._serialized_end=239
  _globals['_PYSUMREQUEST']._serialized_start=241
  _globals['_PYSUMREQUEST']._serialized_end=283
  _globals['_PYSUMRESPONSE']._serialized_start=285
  _globals['_PYSUMRESPONSE']._serialized_end=316
  _globals['_MYSERVICE']._serialized_start=319
  _globals['_MYSERVICE']._serialized_end=588
# @@protoc_insertion_point(module_scope)
